#pragma once

/* RGBLIGHT configuration */
#define WS2812_DI_PIN A9
#define RGBLED_NUM 2
#define RGBLED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 9
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_CHRISTMAS
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#define FORCE_NKRO

#define SPLIT_HAND_PIN B7

#define USB_VBUS_PIN A10
#undef  SPLIT_USB_DETECT
